name: "Test Today's Scripture!"

on:
  # Allow manual execution
  workflow_dispatch:

jobs:
  test-daily-scripture:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup gitHub User Details
        uses: octoleo/git-user@v2
        with:
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-user: ${{ secrets.GPG_USER }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-pub: ${{ secrets.SSH_PUB }}
          git-user: ${{ secrets.GIT_USER }}
          git-email: ${{ secrets.GIT_EMAIL }}

      - name: Clone Master Repository
        run: |
          /bin/git clone git@github.com:trueChristian/daily-scripture.git daily_scripture

      - name: Build the Daily Scripture (Dry Run)
        run: |
          cd daily_scripture
          /bin/bash ./src/today.sh --dry

