name: "Load Today's Scripture Telegram ID!"

on:
  # Run once per day at 23:45 UTC
  schedule:
    - cron: '45 23 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  load-scripture-telegram-id:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup GitHub User Details
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GPG_USER: ${{ secrets.GPG_USER }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PUB: ${{ secrets.SSH_PUB }}
        run: |
          /bin/bash <(/bin/curl -s https://raw.githubusercontent.com/vdm-io/github-user/master/src/setup.sh) \
            --gpg-key "$GPG_KEY" \
            --gpg-user "$GPG_USER" \
            --ssh-key "$SSH_KEY" \
            --ssh-pub "$SSH_PUB" \
            --git-user "$GIT_USER" \
            --git-email "$GIT_EMAIL"

      - name: Clone Daily Scripture Repository
        run: |
          /bin/git clone git@github.com:trueChristian/daily-scripture.git daily_scripture

      - name: Build the Daily Scripture Telegram ID
        env:
          BOT_TOKEN: ${{ secrets.GETBIBLE_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.TG_DAILY_SCRIPTURE_GROUP_ID }}
        run: |
          cd daily_scripture
          /bin/bash ./src/telegram.sh

