name: "Load Today's Scripture Telegram ID!"

on:
  # Run once per day at 23:45 UTC
  schedule:
    - cron: '45 23 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  load-scripture-telegram-id:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup gitHub User Details
        uses: octoleo/git-user@v2
        with:
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-user: ${{ secrets.GPG_USER }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-pub: ${{ secrets.SSH_PUB }}
          git-user: ${{ secrets.GIT_USER }}
          git-email: ${{ secrets.GIT_EMAIL }}

      - name: Clone Daily Scripture Repository
        run: |
          /bin/git clone git@github.com:trueChristian/daily-scripture.git daily_scripture

      - name: Build the Daily Scripture Telegram ID
        env:
          BOT_TOKEN: ${{ secrets.GETBIBLE_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.TG_DAILY_SCRIPTURE_GROUP_ID }}
        run: |
          cd daily_scripture
          /bin/bash ./src/telegram.sh

